name: Docs

on:
  push:
    branches:
      - main

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Generate docs
        run: |
          mkdir out
          dotnet run -- docs out
        working-directory: "samples/Cocona.Docs.Examples.Calc/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./samples/Cocona.Docs.Examples.Calc/out
